name: åŸŸåxyzç»­æœŸæé†’

on:
  schedule:
    - cron: '0 1,5 20 3 *'
  workflow_dispatch:

jobs:
  remind:
    runs-on: ubuntu-latest
    steps:
      - name: è°ƒç”¨åŸŸåxyzæé†’
        run: |
          echo "ğŸ“… åŸŸåxyzç»­æœŸæé†’"
          curl -L "${{ secrets.DOMAIN_A_RENEW_URL }}"
